[package]
name = "unit-test-gen"
version = "0.1.0"
edition = "2024"

[dependencies]

async-openai = { version = "0.32.2", default-features = false, features = ["_api", "rustls", "responses"] }
tracing-attributes = "0.1.30"
anyhow = "1.0.100"
futures = "0.3"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.54", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true          # or "thin" if build times get annoying
codegen-units = 1
panic = "abort"     # usually fine for services/CLIs; can reduce overhead a bit
debug = 0
